[package]
name = "chip-8-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = '0.35.2'

[dev-dependencies]
rustfmt = "0.10.0"

[build-dependencies]
pkg-config = "0.3.27"
